django_tut/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^homepage/', include('homepage.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.conf.urls import url
from . import views

app_name = 'homepage'

urlpatterns = [
    
    #/homepage/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/music/album_id
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='details'),

    #/homepage/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    #homepage/album/2
    url(r'^album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(), name='album-update'),
    
    #homepage/album/2/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(), name='album-delete'),
]

homepage/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_name = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('homepage:details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_name + ' - ' + self.artist
#Class for songs
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

homepage/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username' , 'email' , 'password']

homepage/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.shortcuts import render, redirect
from .models import Album
from .forms import UserForm

class IndexView(generic.ListView):
    template_name = 'homepage/index.html'
    context_object_name = 'all_albums'
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'homepage/details.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_name', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_name', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('homepage:index')

homepage/templates/homepage/album_form.html
{% extends 'homepage/base.html' %}
{% block title %}Add a new Album {% endblock %}
{% block albums_active %}active {% endblock %}
{% block body%}
<div class="panel panel-default">
    <div class="panel-body">
       <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'homepage/form-template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
       </form>
    </div>
</div>
{% endblock %}

homepage/templates/homepage/base.html
<html>
    <head>
    <title>{% block title %}Espada{% endblock %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'homepage/style.css' %}" type="text/css" />
        <!-- Bootstrap CSS-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!--JQuery--> 
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Bubbler+One|Gloria+Hallelujah|Inconsolata|Indie+Flower|Pacifico|Shadows+Into+Light" rel="stylesheet"> 
    </head>
    <body>
                <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href = "{% url 'homepage:index' %}">Espada</a>
                </div>
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'homepage:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'homepage:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>

homepage/templates/homepage/details.html
{% extends 'homepage/base.html' %}	
{% block title %}Albums{% endblock %}	
    {% block body %}
        <img src="{{ album.album_logo.url }}"/>
        <h1>{{album.album_name}}</h1>
        <h2>{{album.artist}}</h2>
        {% if error_message %}
        <p>error_message</p>
        {% endif %}
            {% for song in album.song_set.all %}
            <label for="song{{ forloop.counter }"> 
                {{ song.song_title }}
                {% if song.is_favorite %}
                <img src="http://findicons.com/files/icons/1620/crystal_project/22/knewstuff.png"/>
                {% endif %}
            </label>
            <br>
            {% endfor %}
    {% endblock %}

homepage/templates/homepage/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

homepage/templates/homepage/index.html
 {% extends 'homepage/base.html' %}		
    {% block body %}
        <ul>
            {% for album in all_albums %}
            <li> <a href="{% url 'homepage:details' album.id %}"> {{album.album_name}} 
                
                <form action="{% url 'homepage:album-delete' album.id %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ album.id }}">
                    <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </form>
                
            </li>
            {% endfor %}
        </ul>
    {% endblock %}